name = "LeanGuard"
version = "0.2.0-rc2"
license = "MIT"
defaultTargets = ["LeanGuard", "LeanGuardProofs", "LeanGuardAudit", "leanguard", "leanguard-conformance"]

[[require]]
name = "LeanLTL"
git = "https://github.com/DebarghaG/LeanLTL.git"
rev = "7514f6f035e4b8944299f02ac80ba7145a2a1f29"

[[lean_lib]]
name = "LeanGuard"

[[lean_lib]]
name = "LeanGuardProofs"

[[lean_lib]]
name = "LeanGuardAudit"

[[lean_exe]]
name = "leanguard"
root = "Main"

[[lean_exe]]
name = "leanguard-conformance"
root = "ConformanceMain"
